[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' kit.fontawesome.com cdn.jsdelivr.net fonts.googleapis.com ka-f.fontawesome.com fonts.gstatic.com; style-src 'self' 'unsafe-inline' kit.fontawesome.com cdn.jsdelivr.net fonts.googleapis.com ka-f.fontawesome.com fonts.gstatic.com; style-src 'self' kit.fontawesome.com cdn.jsdelivr.net fonts.googleapis.com ka-f.fontawesome.com fonts.gstatic.com;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), ambient-light-sensor=(), payment=(), usb=(), video=(), audio=()"
    X-Robots-Tag = "noindex, nofollow"
    X-Permitted-Cross-Domain-Policies = "none"
  
