[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self';"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), ambient-light-sensor=(), payment=(), usb=(), video=(), audio=()"
    X-Robots-Tag = "noindex, nofollow"
    X-Permitted-Cross-Domain-Policies = "none"
  
